# Default values for oci-backup-healer.
# This is a YAML-formatted file.

image:
  repository: ghcr.io/wallissonmarinho/oci-backup-healer
  tag: "0.1.10" # Atualizado para nova tag segura
  pullPolicy: IfNotPresent

# IDs do ecossistema de backups (Deixar vazio no repositório público)
primaryVMID: ""
backupVMID: ""
volumeID: ""
backupVMIP: "" # IP da VM 2 (Tailscale) para comandos SSH

# Configurações do Reconciler
reconcileIntervalSecs: 30
unhealthyTimeoutSecs: 300

# Parametros operacionais
dryRun: false
fakeProvider: false

# Notificações ntfy (Deixar vazio no repositório público)
ntfyTopicURL: ""

# Secrets de Autenticação (preenchidos no cluster ou lidos de arquivos locais)
# O ociConfigSecret contem o arquivo config da OCI e a chave de API pem.
ociConfigSecret: "oci-credentials-sp-c"
# O sshKeySecret contem a chave privada ssh para conexao com a VM2 de backup.
sshKeySecret: "oci-backup-ssh-key"
